### ISSUE TITLE
Creative conversion kit's quest and Resonant conversion kit's quest were missplaced

### ISSUE THREAD

**Issue by Fuzzy2319** [BreizhHardware/Recurent-Tech#3]
![image](https://user-images.githubusercontent.com/61144247/102721352-88d74a80-42fa-11eb-9eef-3c654ecd03c9.png)

**Comment by BreizhHardware** [comment]
I will fix it in the next update.

**Comment by BreizhHardware** [comment]
Fixes since one week.
